const contractAddress = "0x04a5a9393BcFf5891e2F8855833025B05b19d4c8"; // Replace with your own contract address
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Are you ready to RAAAGE?!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'we are building the next generation of internet culture within web3 by bringing back the most nostalgic era of meme culture, Rage Comics.';
const h1_presale_coming_soon = "FFFFUUUUU!!";
const h1_presale_mint = "Pre-RAGING is ON!!";
const h1_public_mint = "Public RAGE is ON!!";
const h2_presale_coming_soon = "Pre-RAGE Minting Countdown";
const h2_presale_mint = "Public RAGE Countdown";
const p_presale_coming_soon = "more updates soon FFFFFFUUUUUUU!";
const p_presale_mint_not_whitelisted = "You are not RAGElisted for the pre-RAGE.. 😢";
const p_presale_mint_whitelisted = "You're on the RAGElist for the pre-RAGE! 🎉";
const p_presale_mint_already_minted = "You've already claimed your RAGER. Thank you! 🎉";
const p_public_mint = "No RAGElist needed. Public RAGE is now ON! 🎉";
const button_presale_coming_soon = "Get on the RAGElist";
const button_presale_mint_whitelisted = "Mint Your RAGER";
const button_presale_mint_not_whitelisted = "Get on the RAGElist";
const button_presale_already_minted = "Join the Discord and follow us on Twitter for more";
const button_public_mint = "Mint Your RAGER";
const mint_failed = "🤬FFFFFUUUU- Minting failed.  Please try again.";
